export const playersData = [
  {
    "chance_of_playing_next_round":0,
    "chance_of_playing_this_round":0,
    "code":21205,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":0,
    "cost_change_start_fall":0,
    "dreamteam_count":0,
    "element_type":1,
    "ep_next":"0.0",
    "ep_this":"0.0",
    "event_points":0,
    "first_name":"Tom",
    "form":"0.0",
    "id":28,
    "in_dreamteam":false,
    "news":"Knee injury - Expected back 17 Oct",
    "news_added":"2020-08-15T10:00:11.430596Z",
    "now_cost":45,
    "photo":"21205.jpg",
    "points_per_game":"0.0",
    "second_name":"Heaton",
    "selected_by_percent":"0.1",
    "special":false,
    "squad_number":null,
    "status":"i",
    "team":3,
    "team_code":7,
    "total_points":0,
    "transfers_in":672,
    "transfers_in_event":178,
    "transfers_out":1817,
    "transfers_out_event":316,
    "value_form":"0.0",
    "value_season":"0.0",
    "web_name":"Heaton",
    "minutes":0,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":0,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":0,
    "bonus":0,
    "bps":0,
    "influence":"0.0",
    "creativity":"0.0",
    "threat":"0.0",
    "ict_index":"0.0",
    "influence_rank":431,
    "influence_rank_type":48,
    "creativity_rank":415,
    "creativity_rank_type":28,
    "threat_rank":375,
    "threat_rank_type":26,
    "ict_index_rank":436,
    "ict_index_rank_type":48,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":75,
    "chance_of_playing_this_round":75,
    "code":123354,
    "cost_change_event":-1,
    "cost_change_event_fall":1,
    "cost_change_start":-1,
    "cost_change_start_fall":1,
    "dreamteam_count":0,
    "element_type":2,
    "ep_next":"-0.8",
    "ep_this":"-1.1",
    "event_points":0,
    "first_name":"Kortney",
    "form":"0.0",
    "id":39,
    "in_dreamteam":false,
    "news":"Muscle injury - 75% chance of playing",
    "news_added":"2020-10-01T22:30:14.186065Z",
    "now_cost":44,
    "photo":"123354.jpg",
    "points_per_game":"0.0",
    "second_name":"Hause",
    "selected_by_percent":"0.1",
    "special":false,
    "squad_number":null,
    "status":"d",
    "team":3,
    "team_code":7,
    "total_points":0,
    "transfers_in":584,
    "transfers_in_event":33,
    "transfers_out":2809,
    "transfers_out_event":566,
    "value_form":"0.0",
    "value_season":"0.0",
    "web_name":"Hause",
    "minutes":0,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":0,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":0,
    "bonus":0,
    "bps":0,
    "influence":"0.0",
    "creativity":"0.0",
    "threat":"0.0",
    "ict_index":"0.0",
    "influence_rank":409,
    "influence_rank_type":158,
    "creativity_rank":392,
    "creativity_rank_type":157,
    "threat_rank":351,
    "threat_rank_type":141,
    "ict_index_rank":414,
    "ict_index_rank_type":158,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":null,
    "chance_of_playing_this_round":null,
    "code":184704,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":0,
    "cost_change_start_fall":0,
    "dreamteam_count":0,
    "element_type":3,
    "ep_next":"-0.7",
    "ep_this":"-1.2",
    "event_points":0,
    "first_name":"Marvelous",
    "form":"0.3",
    "id":44,
    "in_dreamteam":false,
    "news":"",
    "news_added":null,
    "now_cost":45,
    "photo":"184704.jpg",
    "points_per_game":"0.5",
    "second_name":"Nakamba",
    "selected_by_percent":"0.4",
    "special":false,
    "squad_number":null,
    "status":"a",
    "team":3,
    "team_code":7,
    "total_points":1,
    "transfers_in":5086,
    "transfers_in_event":466,
    "transfers_out":16956,
    "transfers_out_event":2666,
    "value_form":"0.1",
    "value_season":"0.2",
    "web_name":"Nakamba",
    "minutes":13,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":0,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":1,
    "red_cards":0,
    "saves":0,
    "bonus":0,
    "bps":4,
    "influence":"8.4",
    "creativity":"0.6",
    "threat":"7.0",
    "ict_index":"1.7",
    "influence_rank":299,
    "influence_rank_type":129,
    "creativity_rank":310,
    "creativity_rank_type":151,
    "threat_rank":229,
    "threat_rank_type":122,
    "ict_index_rank":321,
    "ict_index_rank_type":141,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":null,
    "chance_of_playing_this_round":null,
    "code":193488,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":-1,
    "cost_change_start_fall":1,
    "dreamteam_count":0,
    "element_type":3,
    "ep_next":"-1.0",
    "ep_this":"-1.5",
    "event_points":0,
    "first_name":"Anwar",
    "form":"0.0",
    "id":45,
    "in_dreamteam":false,
    "news":"",
    "news_added":null,
    "now_cost":59,
    "photo":"193488.jpg",
    "points_per_game":"0.0",
    "second_name":"El Ghazi",
    "selected_by_percent":"0.1",
    "special":false,
    "squad_number":null,
    "status":"a",
    "team":3,
    "team_code":7,
    "total_points":0,
    "transfers_in":2168,
    "transfers_in_event":190,
    "transfers_out":6773,
    "transfers_out_event":1023,
    "value_form":"0.0",
    "value_season":"0.0",
    "web_name":"El Ghazi",
    "minutes":0,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":0,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":0,
    "bonus":0,
    "bps":0,
    "influence":"0.0",
    "creativity":"0.0",
    "threat":"0.0",
    "ict_index":"0.0",
    "influence_rank":559,
    "influence_rank_type":228,
    "creativity_rank":559,
    "creativity_rank_type":228,
    "threat_rank":558,
    "threat_rank_type":227,
    "ict_index_rank":561,
    "ict_index_rank_type":228,
    "corners_and_indirect_freekicks_order":5,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":2,
    "direct_freekicks_text":"",
    "penalties_order":2,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":null,
    "chance_of_playing_this_round":null,
    "code":199798,
    "cost_change_event":1,
    "cost_change_event_fall":-1,
    "cost_change_start":1,
    "cost_change_start_fall":-1,
    "dreamteam_count":1,
    "element_type":2,
    "ep_next":"6.3",
    "ep_this":"5.8",
    "event_points":1,
    "first_name":"Ezri",
    "form":"7.3",
    "id":46,
    "in_dreamteam":false,
    "news":"",
    "news_added":null,
    "now_cost":46,
    "photo":"199798.jpg",
    "points_per_game":"7.3",
    "second_name":"Konsa Ngoyo",
    "selected_by_percent":"5.1",
    "special":false,
    "squad_number":null,
    "status":"a",
    "team":3,
    "team_code":7,
    "total_points":22,
    "transfers_in":359594,
    "transfers_in_event":97614,
    "transfers_out":80178,
    "transfers_out_event":29196,
    "value_form":"1.6",
    "value_season":"4.8",
    "web_name":"Konsa",
    "minutes":270,
    "goals_scored":1,
    "assists":0,
    "clean_sheets":2,
    "goals_conceded":2,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":0,
    "bonus":3,
    "bps":79,
    "influence":"85.6",
    "creativity":"0.3",
    "threat":"33.0",
    "ict_index":"11.9",
    "influence_rank":57,
    "influence_rank_type":18,
    "creativity_rank":323,
    "creativity_rank_type":121,
    "threat_rank":121,
    "threat_rank_type":26,
    "ict_index_rank":125,
    "ict_index_rank_type":37,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":100,
    "chance_of_playing_this_round":100,
    "code":165809,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":-1,
    "cost_change_start_fall":1,
    "dreamteam_count":0,
    "element_type":3,
    "ep_next":"0.8",
    "ep_this":"1.8",
    "event_points":1,
    "first_name":"Bernardo Mota",
    "form":"0.3",
    "id":281,
    "in_dreamteam":false,
    "news":"",
    "news_added":"2020-09-08T22:30:12.089513Z",
    "now_cost":74,
    "photo":"165809.jpg",
    "points_per_game":"1.0",
    "second_name":"Veiga de Carvalho e Silva",
    "selected_by_percent":"0.4",
    "special":false,
    "squad_number":null,
    "status":"a",
    "team":4,
    "team_code":43,
    "total_points":1,
    "transfers_in":9076,
    "transfers_in_event":3073,
    "transfers_out":36281,
    "transfers_out_event":2701,
    "value_form":"0.0",
    "value_season":"0.1",
    "web_name":"Bernardo Silva",
    "minutes":25,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":0,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":0,
    "bonus":0,
    "bps":5,
    "influence":"3.2",
    "creativity":"12.1",
    "threat":"8.0",
    "ict_index":"2.3",
    "influence_rank":331,
    "influence_rank_type":147,
    "creativity_rank":214,
    "creativity_rank_type":122,
    "threat_rank":228,
    "threat_rank_type":121,
    "ict_index_rank":308,
    "ict_index_rank_type":134,
    "corners_and_indirect_freekicks_order":4,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":0,
    "chance_of_playing_this_round":0,
    "code":205651,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":-1,
    "cost_change_start_fall":1,
    "dreamteam_count":0,
    "element_type":4,
    "ep_next":"0.0",
    "ep_this":"0.0",
    "event_points":0,
    "first_name":"Gabriel Fernando",
    "form":"2.0",
    "id":282,
    "in_dreamteam":false,
    "news":"Muscle injury - Expected back 24 Oct",
    "news_added":"2020-09-25T18:00:17.193627Z",
    "now_cost":94,
    "photo":"205651.jpg",
    "points_per_game":"6.0",
    "second_name":"de Jesus",
    "selected_by_percent":"0.9",
    "special":false,
    "squad_number":null,
    "status":"i",
    "team":4,
    "team_code":43,
    "total_points":6,
    "transfers_in":121407,
    "transfers_in_event":345,
    "transfers_out":193852,
    "transfers_out_event":12624,
    "value_form":"0.2",
    "value_season":"0.6",
    "web_name":"Jesus",
    "minutes":90,
    "goals_scored":1,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":1,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":1,
    "red_cards":0,
    "saves":0,
    "bonus":1,
    "bps":28,
    "influence":"47.0",
    "creativity":"13.8",
    "threat":"45.0",
    "ict_index":"10.6",
    "influence_rank":150,
    "influence_rank_type":16,
    "creativity_rank":198,
    "creativity_rank_type":29,
    "threat_rank":84,
    "threat_rank_type":29,
    "ict_index_rank":138,
    "ict_index_rank_type":22,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":5,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":0,
    "chance_of_playing_this_round":0,
    "code":206325,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":0,
    "cost_change_start_fall":0,
    "dreamteam_count":0,
    "element_type":2,
    "ep_next":"0.0",
    "ep_this":"0.0",
    "event_points":0,
    "first_name":"Oleksandr",
    "form":"0.0",
    "id":283,
    "in_dreamteam":false,
    "news":"Unknown - Expected back 24 Oct",
    "news_added":"2020-10-01T01:00:15.242512Z",
    "now_cost":55,
    "photo":"206325.jpg",
    "points_per_game":"0.0",
    "second_name":"Zinchenko",
    "selected_by_percent":"0.2",
    "special":false,
    "squad_number":null,
    "status":"i",
    "team":4,
    "team_code":43,
    "total_points":0,
    "transfers_in":2660,
    "transfers_in_event":36,
    "transfers_out":18197,
    "transfers_out_event":2585,
    "value_form":"0.0",
    "value_season":"0.0",
    "web_name":"Zinchenko",
    "minutes":0,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":0,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":0,
    "bonus":0,
    "bps":0,
    "influence":"0.0",
    "creativity":"0.0",
    "threat":"0.0",
    "ict_index":"0.0",
    "influence_rank":546,
    "influence_rank_type":209,
    "creativity_rank":548,
    "creativity_rank_type":209,
    "threat_rank":544,
    "threat_rank_type":209,
    "ict_index_rank":549,
    "ict_index_rank_type":209,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":null,
    "chance_of_playing_this_round":null,
    "code":43670,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":-1,
    "cost_change_start_fall":1,
    "dreamteam_count":0,
    "element_type":3,
    "ep_next":"0.5",
    "ep_this":"0.0",
    "event_points":0,
    "first_name":"Juan",
    "form":"0.0",
    "id":290,
    "in_dreamteam":false,
    "news":"",
    "news_added":null,
    "now_cost":59,
    "photo":"43670.jpg",
    "points_per_game":"0.0",
    "second_name":"Mata",
    "selected_by_percent":"0.1",
    "special":false,
    "squad_number":null,
    "status":"a",
    "team":5,
    "team_code":1,
    "total_points":0,
    "transfers_in":2020,
    "transfers_in_event":407,
    "transfers_out":5137,
    "transfers_out_event":931,
    "value_form":"0.0",
    "value_season":"0.0",
    "web_name":"Mata",
    "minutes":0,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":0,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":0,
    "bonus":0,
    "bps":0,
    "influence":"0.0",
    "creativity":"0.0",
    "threat":"0.0",
    "ict_index":"0.0",
    "influence_rank":553,
    "influence_rank_type":224,
    "creativity_rank":554,
    "creativity_rank_type":225,
    "threat_rank":552,
    "threat_rank_type":223,
    "ict_index_rank":555,
    "ict_index_rank_type":224,
    "corners_and_indirect_freekicks_order":4,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":4,
    "direct_freekicks_text":"",
    "penalties_order":5,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":null,
    "chance_of_playing_this_round":null,
    "code":51940,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":0,
    "cost_change_start_fall":0,
    "dreamteam_count":0,
    "element_type":1,
    "ep_next":"1.2",
    "ep_this":"0.7",
    "event_points":-1,
    "first_name":"David",
    "form":"0.7",
    "id":291,
    "in_dreamteam":false,
    "news":"",
    "news_added":null,
    "now_cost":55,
    "photo":"51940.jpg",
    "points_per_game":"0.7",
    "second_name":"de Gea",
    "selected_by_percent":"3.8",
    "special":false,
    "squad_number":null,
    "status":"a",
    "team":5,
    "team_code":1,
    "total_points":2,
    "transfers_in":54144,
    "transfers_in_event":5591,
    "transfers_out":102978,
    "transfers_out_event":22102,
    "value_form":"0.1",
    "value_season":"0.4",
    "web_name":"de Gea",
    "minutes":270,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":11,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":7,
    "bonus":0,
    "bps":36,
    "influence":"62.2",
    "creativity":"0.0",
    "threat":"0.0",
    "ict_index":"6.3",
    "influence_rank":106,
    "influence_rank_type":15,
    "creativity_rank":541,
    "creativity_rank_type":58,
    "threat_rank":538,
    "threat_rank_type":58,
    "ict_index_rank":223,
    "ict_index_rank_type":15,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":0,
    "chance_of_playing_this_round":null,
    "code":55909,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":-1,
    "cost_change_start_fall":1,
    "dreamteam_count":0,
    "element_type":2,
    "ep_next":"0.0",
    "ep_this":"0.0",
    "event_points":0,
    "first_name":"Chris",
    "form":"0.0",
    "id":292,
    "in_dreamteam":false,
    "news":"Joined Roma on a permanent deal on 5/10",
    "news_added":"2020-10-05T20:30:12.521425Z",
    "now_cost":49,
    "photo":"55909.jpg",
    "points_per_game":"0.0",
    "second_name":"Smalling",
    "selected_by_percent":"0.1",
    "special":false,
    "squad_number":null,
    "status":"u",
    "team":5,
    "team_code":1,
    "total_points":0,
    "transfers_in":1800,
    "transfers_in_event":119,
    "transfers_out":8290,
    "transfers_out_event":1735,
    "value_form":"0.0",
    "value_season":"0.0",
    "web_name":"Smalling",
    "minutes":0,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":0,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":0,
    "bonus":0,
    "bps":0,
    "influence":"0.0",
    "creativity":"0.0",
    "threat":"0.0",
    "ict_index":"0.0",
    "influence_rank":488,
    "influence_rank_type":190,
    "creativity_rank":480,
    "creativity_rank_type":190,
    "threat_rank":455,
    "threat_rank_type":180,
    "ict_index_rank":492,
    "ict_index_rank_type":190,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":null,
    "chance_of_playing_this_round":null,
    "code":83427,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":-1,
    "cost_change_start_fall":1,
    "dreamteam_count":0,
    "element_type":2,
    "ep_next":"1.3",
    "ep_this":"0.3",
    "event_points":1,
    "first_name":"Jack",
    "form":"0.8",
    "id":352,
    "in_dreamteam":false,
    "news":"",
    "news_added":null,
    "now_cost":44,
    "photo":"83427.jpg",
    "points_per_game":"1.5",
    "second_name":"Robinson",
    "selected_by_percent":"0.2",
    "special":false,
    "squad_number":null,
    "status":"a",
    "team":6,
    "team_code":49,
    "total_points":3,
    "transfers_in":2698,
    "transfers_in_event":1177,
    "transfers_out":5740,
    "transfers_out_event":842,
    "value_form":"0.2",
    "value_season":"0.7",
    "web_name":"Jack Robinson",
    "minutes":180,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":3,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":0,
    "bonus":0,
    "bps":17,
    "influence":"22.4",
    "creativity":"3.3",
    "threat":"15.0",
    "ict_index":"4.0",
    "influence_rank":241,
    "influence_rank_type":95,
    "creativity_rank":261,
    "creativity_rank_type":85,
    "threat_rank":192,
    "threat_rank_type":54,
    "ict_index_rank":268,
    "ict_index_rank_type":94,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":100,
    "chance_of_playing_this_round":100,
    "code":108416,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":-1,
    "cost_change_start_fall":1,
    "dreamteam_count":0,
    "element_type":2,
    "ep_next":"0.3",
    "ep_this":"-0.7",
    "event_points":1,
    "first_name":"John",
    "form":"-0.2",
    "id":353,
    "in_dreamteam":false,
    "news":"",
    "news_added":"2020-09-21T19:30:15.407006Z",
    "now_cost":49,
    "photo":"108416.jpg",
    "points_per_game":"-0.3",
    "second_name":"Egan",
    "selected_by_percent":"5.3",
    "special":false,
    "squad_number":null,
    "status":"a",
    "team":6,
    "team_code":49,
    "total_points":-1,
    "transfers_in":25647,
    "transfers_in_event":1613,
    "transfers_out":686917,
    "transfers_out_event":36176,
    "value_form":"0.0",
    "value_season":"-0.2",
    "web_name":"Egan",
    "minutes":191,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":5,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":1,
    "red_cards":1,
    "saves":0,
    "bonus":0,
    "bps":8,
    "influence":"20.0",
    "creativity":"1.7",
    "threat":"8.0",
    "ict_index":"3.0",
    "influence_rank":251,
    "influence_rank_type":100,
    "creativity_rank":285,
    "creativity_rank_type":102,
    "threat_rank":220,
    "threat_rank_type":67,
    "ict_index_rank":288,
    "ict_index_rank_type":105,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":0,
    "chance_of_playing_this_round":0,
    "code":146610,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":-1,
    "cost_change_start_fall":1,
    "dreamteam_count":0,
    "element_type":2,
    "ep_next":"0.0",
    "ep_this":"0.0",
    "event_points":0,
    "first_name":"Jack",
    "form":"0.8",
    "id":354,
    "in_dreamteam":false,
    "news":"Knee injury - Unknown return date",
    "news_added":"2020-09-27T12:30:11.602150Z",
    "now_cost":49,
    "photo":"146610.jpg",
    "points_per_game":"1.5",
    "second_name":"O'Connell",
    "selected_by_percent":"0.3",
    "special":false,
    "squad_number":null,
    "status":"i",
    "team":6,
    "team_code":49,
    "total_points":3,
    "transfers_in":3099,
    "transfers_in_event":19,
    "transfers_out":32297,
    "transfers_out_event":4104,
    "value_form":"0.2",
    "value_season":"0.6",
    "web_name":"O'Connell",
    "minutes":180,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":3,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":0,
    "bonus":0,
    "bps":19,
    "influence":"40.2",
    "creativity":"2.5",
    "threat":"0.0",
    "ict_index":"4.3",
    "influence_rank":175,
    "influence_rank_type":68,
    "creativity_rank":274,
    "creativity_rank_type":93,
    "threat_rank":471,
    "threat_rank_type":187,
    "ict_index_rank":262,
    "ict_index_rank_type":90,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":null,
    "chance_of_playing_this_round":null,
    "code":56377,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":-2,
    "cost_change_start_fall":2,
    "dreamteam_count":0,
    "element_type":3,
    "ep_next":"-0.3",
    "ep_this":"-0.3",
    "event_points":0,
    "first_name":"Andriy",
    "form":"0.2",
    "id":436,
    "in_dreamteam":false,
    "news":"",
    "news_added":null,
    "now_cost":58,
    "photo":"56377.jpg",
    "points_per_game":"0.5",
    "second_name":"Yarmolenko",
    "selected_by_percent":"0.1",
    "special":false,
    "squad_number":null,
    "status":"a",
    "team":6,
    "team_code":21,
    "total_points":1,
    "transfers_in":2132,
    "transfers_in_event":176,
    "transfers_out":10824,
    "transfers_out_event":1012,
    "value_form":"0.0",
    "value_season":"0.2",
    "web_name":"Yarmolenko",
    "minutes":30,
    "goals_scored":0,
    "assists":0,
    "clean_sheets":0,
    "goals_conceded":2,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":1,
    "red_cards":0,
    "saves":0,
    "bonus":0,
    "bps":3,
    "influence":"5.0",
    "creativity":"6.3",
    "threat":"26.0",
    "ict_index":"3.7",
    "influence_rank":315,
    "influence_rank_type":141,
    "creativity_rank":240,
    "creativity_rank_type":130,
    "threat_rank":147,
    "threat_rank_type":78,
    "ict_index_rank":274,
    "ict_index_rank_type":125,
    "corners_and_indirect_freekicks_order":4,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":4,
    "direct_freekicks_text":"",
    "penalties_order":null,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round":null,
    "chance_of_playing_this_round":null,
    "code":57531,
    "cost_change_event":0,
    "cost_change_event_fall":0,
    "cost_change_start":-2,
    "cost_change_start_fall":2,
    "dreamteam_count":0,
    "element_type":4,
    "ep_next":"4.0",
    "ep_this":"4.0",
    "event_points":8,
    "first_name":"Michail",
    "form":"4.5",
    "id":437,
    "in_dreamteam":false,
    "news":"",
    "news_added":null,
    "now_cost":63,
    "photo":"57531.jpg",
    "points_per_game":"4.5",
    "second_name":"Antonio",
    "selected_by_percent":"5.2",
    "special":false,
    "squad_number":null,
    "status":"a",
    "team":6,
    "team_code":21,
    "total_points":18,
    "transfers_in":88261,
    "transfers_in_event":29061,
    "transfers_out":423662,
    "transfers_out_event":32167,
    "value_form":"0.7",
    "value_season":"2.9",
    "web_name":"Antonio",
    "minutes":354,
    "goals_scored":2,
    "assists":0,
    "clean_sheets":2,
    "goals_conceded":4,
    "own_goals":0,
    "penalties_saved":0,
    "penalties_missed":0,
    "yellow_cards":0,
    "red_cards":0,
    "saves":0,
    "bonus":2,
    "bps":58,
    "influence":"97.2",
    "creativity":"51.5",
    "threat":"250.0",
    "ict_index":"39.8",
    "influence_rank":45,
    "influence_rank_type":11,
    "creativity_rank":68,
    "creativity_rank_type":5,
    "threat_rank":4,
    "threat_rank_type":3,
    "ict_index_rank":10,
    "ict_index_rank_type":4,
    "corners_and_indirect_freekicks_order":null,
    "corners_and_indirect_freekicks_text":"",
    "direct_freekicks_order":null,
    "direct_freekicks_text":"",
    "penalties_order":2,
    "penalties_text":""
  },
  {
    "chance_of_playing_next_round": null,
    "chance_of_playing_this_round": null,
    "code": 80201,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": 0,
    "cost_change_start_fall": 0,
    "dreamteam_count": 2,
    "element_type": 1,
    "ep_next": "6.8",
    "ep_this": "6.8",
    "event_points": 10,
    "first_name": "Bernd",
    "form": "6.3",
    "id": 8,
    "in_dreamteam": false,
    "news": "",
    "news_added": null,
    "now_cost": 50,
    "photo": "80201.jpg",
    "points_per_game": "4.2",
    "second_name": "Leno",
    "selected_by_percent": "9.0",
    "special": false,
    "squad_number": null,
    "status": "a",
    "team": 1,
    "team_code": 3,
    "total_points": 38,
    "transfers_in": 393442,
    "transfers_in_event": 15603,
    "transfers_out": 368715,
    "transfers_out_event": 12103,
    "value_form": "1.3",
    "value_season": "7.6",
    "web_name": "Leno",
    "minutes": 810,
    "goals_scored": 0,
    "assists": 0,
    "clean_sheets": 3,
    "goals_conceded": 10,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 0,
    "red_cards": 0,
    "saves": 25,
    "bonus": 5,
    "bps": 179,
    "influence": "202.8",
    "creativity": "0.0",
    "threat": "0.0",
    "ict_index": "20.3",
    "influence_rank": 37,
    "influence_rank_type": 9,
    "creativity_rank": 568,
    "creativity_rank_type": 59,
    "threat_rank": 558,
    "threat_rank_type": 59,
    "ict_index_rank": 171,
    "ict_index_rank_type": 8,
    "corners_and_indirect_freekicks_order": null,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": null,
    "direct_freekicks_text": "",
    "penalties_order": null,
    "penalties_text": ""
  },
  {
    "chance_of_playing_next_round": null,
    "chance_of_playing_this_round": null,
    "code": 131897,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": 0,
    "cost_change_start_fall": 0,
    "dreamteam_count": 0,
    "element_type": 1,
    "ep_next": "2.0",
    "ep_this": "3.0",
    "event_points": 3,
    "first_name": "Mathew",
    "form": "3.0",
    "id": 70,
    "in_dreamteam": false,
    "news": "",
    "news_added": null,
    "now_cost": 45,
    "photo": "131897.jpg",
    "points_per_game": "2.5",
    "second_name": "Ryan",
    "selected_by_percent": "13.2",
    "special": false,
    "squad_number": null,
    "status": "a",
    "team": 3,
    "team_code": 36,
    "total_points": 20,
    "transfers_in": 362976,
    "transfers_in_event": 4752,
    "transfers_out": 615202,
    "transfers_out_event": 28576,
    "value_form": "0.7",
    "value_season": "4.4",
    "web_name": "Ryan",
    "minutes": 720,
    "goals_scored": 0,
    "assists": 0,
    "clean_sheets": 2,
    "goals_conceded": 13,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 1,
    "red_cards": 0,
    "saves": 11,
    "bonus": 0,
    "bps": 119,
    "influence": "82.2",
    "creativity": "0.3",
    "threat": "0.0",
    "ict_index": "8.2",
    "influence_rank": 195,
    "influence_rank_type": 19,
    "creativity_rank": 388,
    "creativity_rank_type": 4,
    "threat_rank": 475,
    "threat_rank_type": 46,
    "ict_index_rank": 301,
    "ict_index_rank_type": 19,
    "corners_and_indirect_freekicks_order": null,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": null,
    "direct_freekicks_text": "",
    "penalties_order": null,
    "penalties_text": ""
  },
  {
    "chance_of_playing_next_round": 25,
    "chance_of_playing_this_round": null,
    "code": 98747,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": -1,
    "cost_change_start_fall": 1,
    "dreamteam_count": 1,
    "element_type": 1,
    "ep_next": "1.4",
    "ep_this": "6.8",
    "event_points": 10,
    "first_name": "Nick",
    "form": "7.3",
    "id": 96,
    "in_dreamteam": false,
    "news": "Head injury - 25% chance of playing",
    "news_added": "2020-11-26T14:00:20.660503Z",
    "now_cost": 54,
    "photo": "98747.jpg",
    "points_per_game": "4.9",
    "second_name": "Pope",
    "selected_by_percent": "10.0",
    "special": false,
    "squad_number": null,
    "status": "d",
    "team": 4,
    "team_code": 90,
    "total_points": 39,
    "transfers_in": 155969,
    "transfers_in_event": 3555,
    "transfers_out": 555721,
    "transfers_out_event": 44157,
    "value_form": "1.4",
    "value_season": "7.2",
    "web_name": "Pope",
    "minutes": 720,
    "goals_scored": 0,
    "assists": 0,
    "clean_sheets": 3,
    "goals_conceded": 12,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 0,
    "red_cards": 0,
    "saves": 27,
    "bonus": 8,
    "bps": 156,
    "influence": "203.4",
    "creativity": "0.0",
    "threat": "0.0",
    "ict_index": "20.3",
    "influence_rank": 35,
    "influence_rank_type": 8,
    "creativity_rank": 582,
    "creativity_rank_type": 63,
    "threat_rank": 579,
    "threat_rank_type": 63,
    "ict_index_rank": 172,
    "ict_index_rank_type": 9,
    "corners_and_indirect_freekicks_order": null,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": null,
    "direct_freekicks_text": "",
    "penalties_order": null,
    "penalties_text": ""
  },
  {
    "chance_of_playing_next_round": null,
    "chance_of_playing_this_round": null,
    "code": 109533,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": -2,
    "cost_change_start_fall": 2,
    "dreamteam_count": 0,
    "element_type": 2,
    "ep_next": "0.3",
    "ep_this": "0.8",
    "event_points": 1,
    "first_name": "Emerson",
    "form": "0.3",
    "id": 111,
    "in_dreamteam": false,
    "news": "",
    "news_added": null,
    "now_cost": 48,
    "photo": "109533.jpg",
    "points_per_game": "1.0",
    "second_name": "Palmieri dos Santos",
    "selected_by_percent": "0.1",
    "special": false,
    "squad_number": null,
    "status": "a",
    "team": 5,
    "team_code": 8,
    "total_points": 1,
    "transfers_in": 2836,
    "transfers_in_event": 154,
    "transfers_out": 10515,
    "transfers_out_event": 268,
    "value_form": "0.1",
    "value_season": "0.2",
    "web_name": "Emerson",
    "minutes": 8,
    "goals_scored": 0,
    "assists": 0,
    "clean_sheets": 0,
    "goals_conceded": 0,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 0,
    "red_cards": 0,
    "saves": 0,
    "bonus": 0,
    "bps": 5,
    "influence": "6.2",
    "creativity": "0.7",
    "threat": "0.0",
    "ict_index": "0.7",
    "influence_rank": 386,
    "influence_rank_type": 150,
    "creativity_rank": 379,
    "creativity_rank_type": 146,
    "threat_rank": 519,
    "threat_rank_type": 199,
    "ict_index_rank": 404,
    "ict_index_rank_type": 152,
    "corners_and_indirect_freekicks_order": 5,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": null,
    "direct_freekicks_text": "",
    "penalties_order": null,
    "penalties_text": ""
  },
  {
    "chance_of_playing_next_round": 100,
    "chance_of_playing_this_round": 100,
    "code": 49413,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": 0,
    "cost_change_start_fall": 0,
    "dreamteam_count": 0,
    "element_type": 2,
    "ep_next": "0.0",
    "ep_this": "0.5",
    "event_points": 0,
    "first_name": "James",
    "form": "0.0",
    "id": 129,
    "in_dreamteam": false,
    "news": "",
    "news_added": "2020-11-06T15:00:15.437586Z",
    "now_cost": 45,
    "photo": "49413.jpg",
    "points_per_game": "0.0",
    "second_name": "Tomkins",
    "selected_by_percent": "0.0",
    "special": false,
    "squad_number": null,
    "status": "a",
    "team": 6,
    "team_code": 31,
    "total_points": 0,
    "transfers_in": 1363,
    "transfers_in_event": 156,
    "transfers_out": 1286,
    "transfers_out_event": 83,
    "value_form": "0.0",
    "value_season": "0.0",
    "web_name": "Tomkins",
    "minutes": 0,
    "goals_scored": 0,
    "assists": 0,
    "clean_sheets": 0,
    "goals_conceded": 0,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 0,
    "red_cards": 0,
    "saves": 0,
    "bonus": 0,
    "bps": 0,
    "influence": "0.0",
    "creativity": "0.0",
    "threat": "0.0",
    "ict_index": "0.0",
    "influence_rank": 510,
    "influence_rank_type": 199,
    "creativity_rank": 494,
    "creativity_rank_type": 199,
    "threat_rank": 462,
    "threat_rank_type": 186,
    "ict_index_rank": 511,
    "ict_index_rank_type": 199,
    "corners_and_indirect_freekicks_order": null,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": null,
    "direct_freekicks_text": "",
    "penalties_order": null,
    "penalties_text": ""
  },
  {
    "chance_of_playing_next_round": 100,
    "chance_of_playing_this_round": 100,
    "code": 74230,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": -1,
    "cost_change_start_fall": 1,
    "dreamteam_count": 0,
    "element_type": 2,
    "ep_next": "2.3",
    "ep_this": "2.8",
    "event_points": 2,
    "first_name": "Patrick",
    "form": "2.3",
    "id": 139,
    "in_dreamteam": false,
    "news": "",
    "news_added": "2020-08-15T10:00:11.682747Z",
    "now_cost": 54,
    "photo": "74230.jpg",
    "points_per_game": "2.0",
    "second_name": "van Aanholt",
    "selected_by_percent": "1.0",
    "special": false,
    "squad_number": null,
    "status": "a",
    "team": 6,
    "team_code": 31,
    "total_points": 8,
    "transfers_in": 82336,
    "transfers_in_event": 18603,
    "transfers_out": 23336,
    "transfers_out_event": 4978,
    "value_form": "0.4",
    "value_season": "1.5",
    "web_name": "van Aanholt",
    "minutes": 288,
    "goals_scored": 0,
    "assists": 1,
    "clean_sheets": 0,
    "goals_conceded": 5,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 1,
    "red_cards": 0,
    "saves": 0,
    "bonus": 0,
    "bps": 39,
    "influence": "45.0",
    "creativity": "33.2",
    "threat": "75.0",
    "ict_index": "15.4",
    "influence_rank": 273,
    "influence_rank_type": 107,
    "creativity_rank": 218,
    "creativity_rank_type": 50,
    "threat_rank": 119,
    "threat_rank_type": 21,
    "ict_index_rank": 221,
    "ict_index_rank_type": 68,
    "corners_and_indirect_freekicks_order": 4,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": 2,
    "direct_freekicks_text": "",
    "penalties_order": 2,
    "penalties_text": ""
  },
  {
    "chance_of_playing_next_round": null,
    "chance_of_playing_this_round": null,
    "code": 466955,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": -1,
    "cost_change_start_fall": 1,
    "dreamteam_count": 0,
    "element_type": 3,
    "ep_next": "0.0",
    "ep_this": "0.5",
    "event_points": 0,
    "first_name": "Brandon",
    "form": "0.0",
    "id": 147,
    "in_dreamteam": false,
    "news": "",
    "news_added": null,
    "now_cost": 44,
    "photo": "466955.jpg",
    "points_per_game": "0.0",
    "second_name": "Pierrick",
    "selected_by_percent": "0.1",
    "special": false,
    "squad_number": null,
    "status": "a",
    "team": 6,
    "team_code": 31,
    "total_points": 0,
    "transfers_in": 6742,
    "transfers_in_event": 454,
    "transfers_out": 8091,
    "transfers_out_event": 469,
    "value_form": "0.0",
    "value_season": "0.0",
    "web_name": "Pierrick",
    "minutes": 0,
    "goals_scored": 0,
    "assists": 0,
    "clean_sheets": 0,
    "goals_conceded": 0,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 0,
    "red_cards": 0,
    "saves": 0,
    "bonus": 0,
    "bps": 0,
    "influence": "0.0",
    "creativity": "0.0",
    "threat": "0.0",
    "ict_index": "0.0",
    "influence_rank": 505,
    "influence_rank_type": 194,
    "creativity_rank": 488,
    "creativity_rank_type": 195,
    "threat_rank": 456,
    "threat_rank_type": 181,
    "ict_index_rank": 506,
    "ict_index_rank_type": 194,
    "corners_and_indirect_freekicks_order": null,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": null,
    "direct_freekicks_text": "",
    "penalties_order": null,
    "penalties_text": ""
  },
  {
    "chance_of_playing_next_round": 100,
    "chance_of_playing_this_round": 75,
    "code": 232413,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": -2,
    "cost_change_start_fall": 2,
    "dreamteam_count": 1,
    "element_type": 3,
    "ep_next": "5.3",
    "ep_this": "4.3",
    "event_points": 2,
    "first_name": "Eberechi",
    "form": "5.3",
    "id": 489,
    "in_dreamteam": false,
    "news": "",
    "news_added": "2020-11-17T23:00:19.063388Z",
    "now_cost": 58,
    "photo": "232413.jpg",
    "points_per_game": "2.9",
    "second_name": "Eze",
    "selected_by_percent": "0.7",
    "special": false,
    "squad_number": null,
    "status": "a",
    "team": 6,
    "team_code": 31,
    "total_points": 23,
    "transfers_in": 53010,
    "transfers_in_event": 15816,
    "transfers_out": 48320,
    "transfers_out_event": 4266,
    "value_form": "0.9",
    "value_season": "4.0",
    "web_name": "Eze",
    "minutes": 407,
    "goals_scored": 1,
    "assists": 1,
    "clean_sheets": 0,
    "goals_conceded": 10,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 0,
    "red_cards": 0,
    "saves": 0,
    "bonus": 3,
    "bps": 85,
    "influence": "110.8",
    "creativity": "84.4",
    "threat": "93.0",
    "ict_index": "28.9",
    "influence_rank": 152,
    "influence_rank_type": 51,
    "creativity_rank": 108,
    "creativity_rank_type": 71,
    "threat_rank": 89,
    "threat_rank_type": 49,
    "ict_index_rank": 108,
    "ict_index_rank_type": 61,
    "corners_and_indirect_freekicks_order": 2,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": 3,
    "direct_freekicks_text": "",
    "penalties_order": null,
    "penalties_text": ""
  },
  {
    "chance_of_playing_next_round": null,
    "chance_of_playing_this_round": null,
    "code": 55422,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": -2,
    "cost_change_start_fall": 2,
    "dreamteam_count": 0,
    "element_type": 3,
    "ep_next": "1.7",
    "ep_this": "2.2",
    "event_points": 1,
    "first_name": "Gylfi",
    "form": "1.7",
    "id": 150,
    "in_dreamteam": false,
    "news": "",
    "news_added": null,
    "now_cost": 68,
    "photo": "55422.jpg",
    "points_per_game": "1.7",
    "second_name": "Sigurdsson",
    "selected_by_percent": "0.9",
    "special": false,
    "squad_number": null,
    "status": "a",
    "team": 7,
    "team_code": 11,
    "total_points": 15,
    "transfers_in": 13876,
    "transfers_in_event": 567,
    "transfers_out": 63032,
    "transfers_out_event": 2082,
    "value_form": "0.3",
    "value_season": "2.2",
    "web_name": "Sigurdsson",
    "minutes": 396,
    "goals_scored": 0,
    "assists": 1,
    "clean_sheets": 0,
    "goals_conceded": 8,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 0,
    "red_cards": 0,
    "saves": 0,
    "bonus": 0,
    "bps": 62,
    "influence": "68.0",
    "creativity": "96.8",
    "threat": "76.0",
    "ict_index": "24.1",
    "influence_rank": 213,
    "influence_rank_type": 85,
    "creativity_rank": 88,
    "creativity_rank_type": 59,
    "threat_rank": 118,
    "threat_rank_type": 65,
    "ict_index_rank": 143,
    "ict_index_rank_type": 74,
    "corners_and_indirect_freekicks_order": 2,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": 3,
    "direct_freekicks_text": "",
    "penalties_order": 1,
    "penalties_text": ""
  },
  {
    "chance_of_playing_next_round": null,
    "chance_of_playing_this_round": null,
    "code": 177815,
    "cost_change_event": 1,
    "cost_change_event_fall": -1,
    "cost_change_start": 9,
    "cost_change_start_fall": -9,
    "dreamteam_count": 2,
    "element_type": 4,
    "ep_next": "8.7",
    "ep_this": "9.2",
    "event_points": 13,
    "first_name": "Dominic",
    "form": "8.7",
    "id": 164,
    "in_dreamteam": true,
    "news": "",
    "news_added": null,
    "now_cost": 79,
    "photo": "177815.jpg",
    "points_per_game": "7.8",
    "second_name": "Calvert-Lewin",
    "selected_by_percent": "60.8",
    "special": false,
    "squad_number": null,
    "status": "a",
    "team": 7,
    "team_code": 11,
    "total_points": 70,
    "transfers_in": 4228875,
    "transfers_in_event": 215627,
    "transfers_out": 692384,
    "transfers_out_event": 21508,
    "value_form": "1.1",
    "value_season": "8.9",
    "web_name": "Calvert-Lewin",
    "minutes": 788,
    "goals_scored": 10,
    "assists": 1,
    "clean_sheets": 1,
    "goals_conceded": 16,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 1,
    "red_cards": 0,
    "saves": 0,
    "bonus": 10,
    "bps": 275,
    "influence": "382.0",
    "creativity": "88.0",
    "threat": "502.0",
    "ict_index": "97.2",
    "influence_rank": 4,
    "influence_rank_type": 2,
    "creativity_rank": 101,
    "creativity_rank_type": 11,
    "threat_rank": 2,
    "threat_rank_type": 1,
    "ict_index_rank": 6,
    "ict_index_rank_type": 2,
    "corners_and_indirect_freekicks_order": null,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": null,
    "direct_freekicks_text": "",
    "penalties_order": null,
    "penalties_text": ""
  },
  {
    "chance_of_playing_next_round": null,
    "chance_of_playing_this_round": null,
    "code": 128389,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": -3,
    "cost_change_start_fall": 3,
    "dreamteam_count": 0,
    "element_type": 4,
    "ep_next": "2.3",
    "ep_this": "2.8",
    "event_points": 1,
    "first_name": "Aleksandar",
    "form": "3.3",
    "id": 184,
    "in_dreamteam": false,
    "news": "",
    "news_added": null,
    "now_cost": 57,
    "photo": "128389.jpg",
    "points_per_game": "3.2",
    "second_name": "Mitrović",
    "selected_by_percent": "5.9",
    "special": false,
    "squad_number": null,
    "status": "a",
    "team": 8,
    "team_code": 54,
    "total_points": 29,
    "transfers_in": 478971,
    "transfers_in_event": 4025,
    "transfers_out": 1622146,
    "transfers_out_event": 53175,
    "value_form": "0.6",
    "value_season": "5.1",
    "web_name": "Mitrović",
    "minutes": 689,
    "goals_scored": 2,
    "assists": 2,
    "clean_sheets": 1,
    "goals_conceded": 12,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 1,
    "yellow_cards": 2,
    "red_cards": 0,
    "saves": 0,
    "bonus": 3,
    "bps": 72,
    "influence": "139.2",
    "creativity": "130.1",
    "threat": "339.0",
    "ict_index": "59.5",
    "influence_rank": 94,
    "influence_rank_type": 14,
    "creativity_rank": 54,
    "creativity_rank_type": 5,
    "threat_rank": 14,
    "threat_rank_type": 9,
    "ict_index_rank": 21,
    "ict_index_rank_type": 11,
    "corners_and_indirect_freekicks_order": null,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": 2,
    "direct_freekicks_text": "",
    "penalties_order": 2,
    "penalties_text": ""
  },
  {
    "chance_of_playing_next_round": null,
    "chance_of_playing_this_round": null,
    "code": 106617,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": 6,
    "cost_change_start_fall": -6,
    "dreamteam_count": 1,
    "element_type": 4,
    "ep_next": "3.7",
    "ep_this": "3.2",
    "event_points": 2,
    "first_name": "Patrick",
    "form": "3.7",
    "id": 202,
    "in_dreamteam": false,
    "news": "",
    "news_added": null,
    "now_cost": 61,
    "photo": "106617.jpg",
    "points_per_game": "6.7",
    "second_name": "Bamford",
    "selected_by_percent": "35.6",
    "special": false,
    "squad_number": null,
    "status": "a",
    "team": 10,
    "team_code": 2,
    "total_points": 60,
    "transfers_in": 3023050,
    "transfers_in_event": 105997,
    "transfers_out": 1004015,
    "transfers_out_event": 106115,
    "value_form": "0.6",
    "value_season": "9.8",
    "web_name": "Bamford",
    "minutes": 760,
    "goals_scored": 7,
    "assists": 2,
    "clean_sheets": 3,
    "goals_conceded": 16,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 1,
    "red_cards": 0,
    "saves": 0,
    "bonus": 9,
    "bps": 199,
    "influence": "281.6",
    "creativity": "58.7",
    "threat": "469.0",
    "ict_index": "80.9",
    "influence_rank": 9,
    "influence_rank_type": 4,
    "creativity_rank": 152,
    "creativity_rank_type": 22,
    "threat_rank": 4,
    "threat_rank_type": 3,
    "ict_index_rank": 8,
    "ict_index_rank_type": 3,
    "corners_and_indirect_freekicks_order": null,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": null,
    "direct_freekicks_text": "",
    "penalties_order": 2,
    "penalties_text": ""
  }









]